name: Update stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:      

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests python-dateutil lxml
      - run: python main.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: wklnd
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update stats"
